# Generated by Django 4.2 on 2023-05-12 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_song_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='attachment',
            field=models.FileField(default=None, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg'])]),
        ),
    ]
