# Generated by Django 4.2 on 2023-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_song_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=None, upload_to='audio/'),
        ),
    ]
