# Generated by Django 4.2.1 on 2023-05-17 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_song_artist_name_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='attachment',
            field=models.FileField(default=None, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
